# Generated by Django 5.0.3 on 2024-03-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset_table',
            old_name='asset_name',
            new_name='asset_code',
        ),
    ]
