# Generated by Django 5.0.3 on 2024-03-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_asset_name_asset_table_asset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit_table',
            name='in_loc_ts',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='kit_table',
            name='out_loc_ts',
            field=models.DateTimeField(),
        ),
    ]
