# Generated by Django 5.0.3 on 2024-03-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_kit_table_in_loc_ts_alter_kit_table_out_loc_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit_table',
            name='in_loc_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kit_table',
            name='out_loc_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
