# Generated by Django 5.0.3 on 2024-03-17 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_kit_table_in_loc_ts_alter_kit_table_out_loc_ts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit_table',
            name='out_loc_place',
        ),
        migrations.RemoveField(
            model_name='kit_table',
            name='out_loc_ts',
        ),
        migrations.CreateModel(
            name='Kit_table2',
            fields=[
                ('kit_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('out_loc_place', models.CharField(max_length=256)),
                ('out_loc_ts', models.DateTimeField(blank=True, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asset_table')),
            ],
        ),
    ]
