# Generated by Django 5.0.3 on 2024-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_newtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_table',
            name='uid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kit_table',
            name='in_loc_place',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kit_table',
            name='kit_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kit_table2',
            name='kit_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kit_table2',
            name='out_loc_place',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='in_loc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='out_loc',
            field=models.TextField(),
        ),
    ]
