# Generated by Django 5.0.3 on 2024-04-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_asset_table_uid_alter_kit_table_in_loc_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_table',
            name='asset_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='asset_table',
            name='asset_desc',
            field=models.CharField(max_length=255),
        ),
    ]
