# Generated by Django 5.0.3 on 2024-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_asset_table_asset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_table',
            name='tpi_ins',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset_table',
            name='tpi_ren',
            field=models.DateField(blank=True, null=True),
        ),
    ]
