# Generated by Django 5.0.3 on 2024-04-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_asset_table_tpi_ins_asset_table_tpi_ren'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_table',
            name='TPI_ins',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset_table',
            name='TPI_ren',
            field=models.TextField(blank=True, null=True),
        ),
    ]
