# Generated by Django 5.0.3 on 2024-03-14 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_table',
            fields=[
                ('uid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=256)),
                ('asset_desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Kit_table',
            fields=[
                ('kit_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('in_loc_place', models.CharField(max_length=256)),
                ('in_loc_ts', models.DateTimeField(auto_now_add=True)),
                ('out_loc_place', models.CharField(max_length=256)),
                ('out_loc_ts', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asset_table')),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_loc', models.CharField(max_length=256)),
                ('out_loc', models.CharField(max_length=256)),
                ('kit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kit_table')),
            ],
        ),
    ]
